### ISSUE TITLE
qt_wallet does not show accounts

### ISSUE THREAD

**Issue by camponez** [BitShares/bitshares#1414]
I'm a bit confuse about the behaviour of the qt_wallet and bitshares_client (command line).

First of all: I see no accounts on the qt_wallet. However, I can see details from one of my accounts. Same detail I see when I try:  blockchain_get_account "my account"

'wallet_list' return 3 results, but I can see nothing about them when I open the qt_client.

- I'm able to see the exchange and everything else (I guess) on the qt_wallet, but my balance is still 0 and someone said that had sent me some BTS.

- Why I can't see my address when using qt_wallet like I do when I blockchain_get_account on the bitshares_client?

- On a previous version (0.6.1) that I compiled I could use the console inside the qt_client, was it removed?

I'm not sure if I don't understand how wallets and accounts works or if the client is not working properly!

**Comment by vikramrajkumar** [comment]
> First of all: I see no accounts on the qt_wallet. However, I can see details from one of my accounts. Same detail I see when I try: blockchain_get_account "my account"

Are you using latest 0.6.2 version with latest 0.6.2-b web_wallet patches? There was a bug without accounts not showing that should have been fixed recently.

> 'wallet_list' return 3 results, but I can see nothing about them when I open the qt_client.

qt_wallet does not support multiple wallets, and only uses the one named default.

> I'm able to see the exchange and everything else (I guess) on the qt_wallet, but my balance is still 0 and someone said that had sent me some BTS.

Make sure you are using the latest code and your accounts are showing up before we try to troubleshoot this.

> Why I can't see my address when using qt_wallet like I do when I blockchain_get_account on the bitshares_client?

We don't expose addresses in the GUI. I think you should still be able to see your public key on a Keys tab somewhere.

> On a previous version (0.6.1) that I compiled I could use the console inside the qt_client, was it removed?

If you go to Advanced there is a console tab.

**Comment by camponez** [comment]
>>First of all: I see no accounts on the qt_wallet. However, I can see details from one of my accounts. >>Same detail I see when I try: blockchain_get_account "my account"

>Are you using latest 0.6.2 version with latest 0.6.2-b web_wallet patches? There was a bug without >accounts not showing that should have been fixed recently.

I'm building the master branch. Isn't this patch already on the master branch? I've seen the message about the patch. I said 'Yes' to the message to installed this 0.6.2-b patch, I still see no accounts. Should I see at least one? It shows "Pay Rate" "Current Rank", etc on the Account details. But I cannot see the other accounts I can see using the console client: wallet_list_accounts


>> Why I can't see my address when using qt_wallet like I do when I blockchain_get_account on the bitshares_client?

>We don't expose addresses in the GUI. I think you should still be able to see your public key on a Keys tab somewhere.

I see no Keys tab.

**Comment by vikramrajkumar** [comment]
@valzav Can you take a look at this?

**Comment by valzav** [comment]
@camponez, if there are no accounts shown in qt wallet, how do you select the one that has details? Did you try to reload a page in qt wallet? (right click somewhere and select Reload) Does it return accounts? Can you transactions?

**Comment by camponez** [comment]
@valzav good question. The screen loads with it. I don't select anything. I'm supposed to see a balance, at least 1BTS but I see none.

I have tried reload. Nothing.

**Comment by valzav** [comment]
did you try to install prebuilt wallet?

**Comment by camponez** [comment]
Last time I tried, for Linux there was only a console client.

**Comment by valzav** [comment]
try to run cli client this way:
 ./programs/client/bitshares_client --server --rpcuser=user --rpcpassword=pass --httpport=5680
then open http://localhost:5680 in a browser and look at js errors in the dev console

**Comment by camponez** [comment]
Should I have to use this user / pass? If so, I get *Invalid RPC Request*

**Comment by valzav** [comment]
oh.. forgot to mention - you need web_wallet's html and css files (https://github.com/BitShares/web_wallet) and have a symlink in your current directory: htdocs -> web_walet's dist or generated dir.

**Comment by camponez** [comment]
Exactly the same thing. 

Where should I see those errors?

**Comment by valzav** [comment]
So you are able to see the gui in browser? Errors (if there are any) can be shown in the development console - just right click on some element and select Inspect Element.

**Comment by camponez** [comment]
Exactly the same thing. 

I could see nothing on Firefox. 

But this is what i got in chrome, after a reload:

 Error in event handler for (unknown): TypeError: Cannot set property 'urlBlackList' of null
    at chrome-extension://hipbfijinpcgfogaopmgehiegacbhmob/extension/chromeMini.js:32:34extensions::uncaught_exception_handler:8 handlerextensions::uncaught_exception_handler:100 exports.handleextensions::event_bindings:384 EventImpl.dispatch_extensions::event_bindings:401 EventImpl.dispatchextensions::SafeBuiltins:19 target.(anonymous function)extensions::utils:94 $Array.forEach.publicClass.(anonymous function)extensions::messaging:304 dispatchOnMessage

**Comment by vikramrajkumar** [comment]
Other possibly related reports:
- https://bitsharestalk.org/index.php?topic=14545.msg190595#msg190595
- https://bitsharestalk.org/index.php?topic=14680.msg190457#msg190457
